server:
    port: 8889
    context-path: /bb/admin
#logging:
#  level:
#    root: info
#    com.vigekoo: debug
#  file: log.log
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
#            first:  #数据源1
#                url: jdbc:mysql://58.2.221.69:3306/a710009498?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#                username: a710009498
#                password: a710009498
            url: jdbc:mysql://192.168.0.88:3306/boot-cms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            username: root
            password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true